// The snapshot module against the REAL trees playwright-core 1.62.1 rendered for the app-factory
// builds (fixtures/snapshots/*, regenerated by fixtures/snapshots/generate.mjs): the 952-line
// bookstore compacts to ≤ 90 lines, the box-join finds an element for 100 % of the interactive
// lines, `find` stays at ≤ 10 lines, `--names` adds the container label (≤ 60 chars) only when
// asked, and a ref like `f3e7` goes to the page literally (AC-9, AC-10).
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { REF_NOT_FOUND } from '../src/print.mjs';
import { maskSnapshotValues } from '../src/redact.mjs';
import {
  CONTEXT_ROLES,
  FIND_MAX,
  INTERACTIVE_ROLES,
  RefNotFoundError,
  aroundRef,
  boxJoin,
  compactLines,
  compactSnapshot,
  diffSnapshot,
  findInSnapshot,
  implicitRole,
  locatorFor,
  locatorForElement,
  namesContext,
  parseSnapshot,
  resolveRef,
  sensitiveRefs,
  sidecarFromPage,
  snapshotArtifacts,
  textUnder,
  uniqueIn,
  walkInteractive,
} from '../src/snapshot.mjs';

const fixtures = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'fixtures', 'snapshots');
const read = (/** @type {string} */ name) => readFileSync(path.join(fixtures, name), 'utf8');

const bookstore = read('bookstore.ai.yml');
const bookstoreBoxes = read('bookstore.boxes.yml');
/** @type {import('../src/snapshot.mjs').WalkEntry[]} */
const walk = JSON.parse(read('walk.json'));
const wizard = read('wizard.ai.yml');

const sidecar = boxJoin(bookstoreBoxes, walk).entries;
const compact = compactLines(bookstore, { sidecar });

/** Refs of every aria line whose role is interactive — what the compact must never lose (unfolded). */
const interactiveRefs = parseSnapshot(bookstore)
  .filter((n) => n.ref && INTERACTIVE_ROLES.has(n.role))
  .map((n) => /** @type {string} */ (n.ref));

describe('parseSnapshot', () => {
  it('reads the 952-line bookstore tree into nodes with refs, names, attrs, urls and inline values', () => {
    expect(bookstore.split('\n').length).toBe(952);
    const nodes = parseSnapshot(bookstore);
    expect(nodes.filter((n) => n.ref).length).toBe(829);
    const search = nodes.find((n) => n.ref === 'e39');
    expect(search).toMatchObject({ role: 'textbox', name: 'Szukaj produktów…', depth: 6 });
    const brand = nodes.find((n) => n.ref === 'e11');
    expect(brand).toMatchObject({ role: 'link', name: 'Księgarnia', url: '/' });
    const skip = nodes.find((n) => n.ref === 'e4');
    expect(skip?.url).toBe('#main-content'); // was `"#main-content"` — YAML-quoted, unquoted here
    const filter = nodes.find((n) => n.ref === 'e79');
    expect(filter?.placeholder).toBe('Tytuł, autor, ISBN');
    const genre = nodes.find((n) => n.ref === 'e81');
    expect(genre?.attrs).toMatchObject({ expanded: true, cursor: 'pointer' });
    const heading = nodes.find((n) => n.ref === 'e69');
    expect(heading).toMatchObject({ role: 'heading', name: 'Filtry', attrs: { level: '2' } });
    const price = nodes.find((n) => n.ref === 'e218');
    expect(price?.text).toBe('69,00 zł');
    const leaf = nodes.find((n) => n.kind === 'text' && n.text === 'Do koszyka');
    expect(leaf && nodes[leaf.parent].parent >= 0 && nodes[nodes[leaf.parent].parent].ref).toBe('e221');
  });

  it('parses boxes and a single-quoted key whose name contains a colon', () => {
    const boxed = parseSnapshot(bookstoreBoxes).find((n) => n.ref === 'e41');
    expect(boxed?.box).toEqual([1184, 12, 36, 36]);
    const step = parseSnapshot(wizard).find((n) => n.ref === 'f1e13');
    expect(step).toMatchObject({ role: 'listitem', name: 'Otwórz krok 1: Dane firmy', attrs: { cursor: 'pointer' } });
  });

  it('tolerates quoted values, escaped quotes, comments and CRLF', () => {
    const yaml = [
      '# comment',
      '- generic [ref=e1]:',
      '  - link "Say \\"hi\\"" [ref=e2] [cursor=pointer]:',
      "    - /url: 'a:b'",
      '  - textbox "Q" [active] [ref=e3]: "x: y"',
      '  - \'button "A: B" [ref=e4]\': done',
      '  - text: "quoted leaf"',
      '',
    ].join('\r\n');
    const nodes = parseSnapshot(yaml);
    expect(nodes.map((n) => n.ref ?? n.kind)).toEqual(['e1', 'e2', 'e3', 'e4', 'text']);
    expect(nodes[1]).toMatchObject({ name: 'Say "hi"', url: 'a:b' });
    expect(nodes[2].text).toBe('x: y');
    expect(nodes[3]).toMatchObject({ role: 'button', name: 'A: B', text: 'done' });
    expect(nodes[4].text).toBe('quoted leaf');
  });
});

describe('compactSnapshot — bookstore 952 lines → ≤ 90 lines', () => {
  it('stays within 90 lines and ends every line without YAML noise', () => {
    expect(compact.length).toBeLessThanOrEqual(90);
    expect(compact.length).toBeGreaterThan(30);
    for (const line of compact) {
      expect(line).not.toMatch(/\[ref=|\[box=|\[cursor=|\[active\]|\[level=|^\s/u);
      expect(line.length).toBeLessThanOrEqual(160);
    }
    expect(compactSnapshot(bookstore, { sidecar })).toBe(`${compact.join('\n')}\n`);
    expect(compactSnapshot('')).toBe('');
  });

  it('renders the DESIGN.md §4.3 line format: ref, role, "name", attrs, → url, selector', () => {
    expect(compact).toContain('e41 button "Szukaj" [data-testid=search-submit]');
    expect(compact).toContain('e45 button "Otwórz koszyk" [data-testid=header-cart-button]');
    expect(compact).toContain('e11 link "Księgarnia" → / [data-testid=header-brand]');
    expect(compact).toContain('e19 link "Nowości" → /new');
    expect(compact).toContain('e39 textbox "Szukaj produktów…" [data-testid=search-input]');
    expect(compact).toContain('e81 button "Gatunek" [expanded] #mat-expansion-panel-header-0');
    expect(compact).toContain('h2 "Filtry"');
    expect(compact).toContain('h1 "Księgarnia (33)"');
    expect(compact).toContain('e186 combobox "Sortuj" [data-testid=catalogue-sort]');
    expect(compact).toContain('e199 img "Bloomsbury Harry Potter and the Philosopher\'s Stone"');
    // A nameless link shows the text it wraps — that is what the screen shows.
    expect(compact).toContain('e58 link "Zobacz katalog arrow_forward" → / [data-testid=shop-hero-cta]');
  });

  it('keeps only interactive and semantic roles; generic, landmarks and paragraphs are gone', () => {
    const roles = new Set(compact.map((l) => l.split(' ')[1]).filter((r) => r && !/^"/u.test(r)));
    for (const role of roles)
      expect(['generic', 'main', 'banner', 'navigation', 'paragraph', 'list', 'listitem']).not.toContain(role);
    expect(compact.some((l) => /^h[1-6] "/u.test(l))).toBe(true);
    expect(compact.filter((l) => /^e\d+ checkbox /u.test(l)).length).toBe(11);
  });

  it('folds runs of look-alike siblings and names what it hid; unfolded keeps every interactive ref', () => {
    const fold = compact.find((l) => l.startsWith('… ×32 similar (e228–e1220)'));
    expect(fold).toBeDefined();
    expect(fold).toContain('"Penguin 1984"');
    expect(fold).toContain('browser-inspector find <text>');
    const unfolded = compactLines(bookstore, { sidecar, fold: false });
    expect(unfolded.length).toBeGreaterThan(compact.length);
    const refsShown = new Set(unfolded.map((l) => l.split(' ')[0]));
    for (const ref of interactiveRefs) expect(refsShown.has(ref), ref).toBe(true);
    // 136 lines match `- <role>` at line start plus 3 whose key is YAML-quoted (a `:` in the name).
    expect(interactiveRefs.length).toBe(139);
    expect(unfolded.some((l) => l.startsWith('…'))).toBe(false);
  });

  it('does not fold short runs (the three footer links stay) and never folds under --grep', () => {
    expect(compact).toContain('e1231 link "O sklepie" → #about');
    expect(compact).toContain('e1235 link "Kariera" → #careers');
    const grep = compactLines(bookstore, { sidecar, grep: 'do koszyka' });
    expect(grep.length).toBe(33);
    expect(grep.every((l) => /^e\d+ button "add_shopping_cart Do koszyka"$/u.test(l))).toBe(true);
  });

  it('renders typed values as `= value`, never for sensitive refs, in the form redact.mjs masks', () => {
    const yaml = [
      '- generic [ref=e1]:',
      '  - textbox "Szukaj produktów…" [active] [ref=e39]: Harry',
      '  - textbox "Hasło" [ref=e40]: tajne',
      '  - textbox "Kod" [ref=e41]: 123456',
      '',
    ].join('\n');
    const side = [
      { ref: 'e39', role: 'textbox', name: 'Szukaj produktów…', selector: '[name="q"]' },
      { ref: 'e40', role: 'textbox', name: 'Hasło', selector: '[name="password"]', sensitive: true },
      { ref: 'e41', role: 'textbox', name: 'Kod', sensitive: true },
    ];
    const lines = compactLines(yaml, { sidecar: side });
    expect(lines).toEqual([
      'e39 textbox "Szukaj produktów…" [name=q] = Harry',
      'e40 textbox "Hasło" [name=password]',
      'e41 textbox "Kod"',
    ]);
    expect(sensitiveRefs(side)).toEqual(['e40', 'e41']);
    // Second belt: the shared masking function recognises the compact line shape.
    const masked = maskSnapshotValues('e39 textbox "Szukaj produktów…" [name=q] = Harry', { sensitiveRefs: ['e39'] });
    expect(masked).toBe('e39 textbox "Szukaj produktów…" [name=q]');
    expect(maskSnapshotValues(lines[0], { secretValues: ['Harry'] })).toBe(
      'e39 textbox "Szukaj produktów…" [name=q] = ***',
    );
  });

  it('keeps alert/status/dialog with their text, and named clickable non-interactive roles', () => {
    const yaml = [
      '- generic [ref=e1]:',
      '  - status [ref=e2]: Zapisano',
      '  - alert [ref=e3]:',
      '    - generic [ref=e4]:',
      '      - text: Błąd zapisu',
      '  - dialog "Usunąć?" [ref=e5]:',
      '    - button "Tak" [ref=e6]',
      '  - generic [ref=e7] [cursor=pointer]',
      '  - listitem "Otwórz krok 1" [ref=e8] [cursor=pointer]',
      '  - img [ref=e9]: star',
      '  - checkbox "Zgoda" [checked] [active] [ref=e10]',
      '  - button "Wyślij" [disabled] [ref=e11]',
      '',
    ].join('\n');
    expect(compactLines(yaml)).toEqual([
      'e2 status: Zapisano',
      'e3 alert: Błąd zapisu',
      'e5 dialog "Usunąć?"',
      'e6 button "Tak"',
      'e8 listitem "Otwórz krok 1"',
      'e10 checkbox "Zgoda" [checked]',
      'e11 button "Wyślij" [disabled]',
    ]);
  });
});

describe('wizard — refs after navigation are f1eN and pass literally', () => {
  it('keeps f<seq>eN refs verbatim and lists the clickable steps', () => {
    const lines = compactLines(wizard);
    expect(lines.length).toBeLessThanOrEqual(20);
    expect(lines).toContain('f1e13 listitem "Otwórz krok 1: Dane firmy"');
    expect(lines).toContain('f1e97 link "Przejdź do podsumowania" → /wizard/6');
    expect(lines.every((l) => /^(f1e\d+ |h\d )/u.test(l))).toBe(true);
    expect(aroundRef(wizard, 'f1e93', { n: 1 })).toEqual([
      'f1e78 listitem "Otwórz krok 6: Podsumowanie"',
      'f1e93 button "Resetuj kreator"',
      'f1e97 link "Przejdź do podsumowania" → /wizard/6',
    ]);
  });
});

describe('boxJoin — sidecar from the boxes snapshot and the DOM walk', () => {
  it('finds an element for 100 % of the interactive lines on the bookstore', () => {
    const { entries, interactive, matched } = boxJoin(bookstoreBoxes, walk);
    expect(interactive).toBeGreaterThanOrEqual(136);
    expect(matched).toBe(interactive);
    for (const entry of entries) {
      expect(entry).toMatchObject({
        ref: expect.stringMatching(/^e\d+$/u),
        role: expect.any(String),
        name: expect.any(String),
      });
      expect(entry.box).toHaveLength(4);
      if (entry.selector) expect(entry.selector).toMatch(/^(\[data-testid=|#|\[id=|\[name=|a\[href=|role=)/u);
    }
    const byRef = new Map(entries.map((e) => [e.ref, e]));
    expect(byRef.get('e41')?.selector).toBe('[data-testid="search-submit"]');
    expect(byRef.get('e95')?.selector).toBe('#mat-mdc-checkbox-1-input');
    expect(byRef.get('e207')?.selector).toBe('role=link[name="Harry Potter and the Philosopher\'s Stone"]');
    expect(byRef.get('e207')?.url).toBe('/book/book-013');
    // Headings and images are in the sidecar (they have refs) but carry no selector.
    expect(byRef.get('e69')).toMatchObject({ role: 'heading', name: 'Filtry' });
    expect(byRef.get('e69')?.selector).toBeUndefined();
  });

  it('prefers data-testid → #id → [name] → a[href] → role=, skipping non-unique attributes', () => {
    const yaml = [
      '- generic [ref=e1] [box=0,0,100,100]:',
      '  - button "A" [ref=e2] [box=0,0,10,10]',
      '  - textbox "B" [ref=e3] [box=0,10,10,10]',
      '  - textbox "C" [ref=e4] [box=0,20,10,10]',
      '  - link "D" [ref=e5] [box=0,30,10,10]:',
      '    - /url: /d',
      '  - button "E" [ref=e6] [box=0,40,10,10]',
      '  - link "F" [ref=e7] [box=0,50,10,10]',
      '  - link "G" [ref=e8] [box=0,60,10,10]',
      '  - textbox "H" [ref=e9] [box=0,70,10,10]',
      '  - textbox "I" [ref=e10] [box=0,80,10,10]',
      '',
    ].join('\n');
    /** @type {import('../src/snapshot.mjs').WalkEntry[]} */
    const w = [
      { tag: 'button', testid: 'a', id: 'a', box: [0, 0, 10, 10] },
      { tag: 'input', type: 'text', id: 'b', nameAttr: 'b', box: [0, 10, 10, 10] },
      { tag: 'input', type: 'text', nameAttr: 'c', box: [0, 20, 10, 10] },
      { tag: 'a', href: '/d', box: [0, 30, 10, 10] },
      { tag: 'button', label: 'E', box: [0, 40, 10, 10] },
      { tag: 'a', href: '/same', testid: 'nav', box: [0, 50, 10, 10] },
      { tag: 'a', href: '/same', testid: 'nav', box: [0, 60, 10, 10] },
      { tag: 'input', type: 'password', nameAttr: 'pw', box: [0, 70, 10, 10] },
      { tag: 'input', type: 'text', nameAttr: 'otp', sensitive: true, box: [0, 80, 10, 10] },
    ];
    const { entries, matched, interactive } = boxJoin(yaml, w);
    expect(matched).toBe(interactive);
    const sel = Object.fromEntries(entries.map((e) => [e.ref, e.selector]));
    expect(sel).toEqual({
      e2: '[data-testid="a"]',
      e3: '#b',
      e4: '[name="c"]',
      e5: 'a[href="/d"]',
      e6: 'role=button[name="E"]',
      e7: 'role=link[name="F"]',
      e8: 'role=link[name="G"]',
      e9: '[name="pw"]',
      e10: '[name="otp"]',
    });
    expect(entries.find((e) => e.ref === 'e10')?.sensitive).toBe(true);
    // `walkInteractive` marks type=password itself; a caller-provided walk may omit `sensitive`,
    // so the join does not invent it — the in-page walk is the source of truth.
    expect(entries.find((e) => e.ref === 'e9')?.sensitive).toBeUndefined();
  });

  it('disambiguates a link and the button inside it sharing one box by role, tolerates ±1 px', () => {
    const yaml = [
      '- link "Go" [ref=e1] [box=0,0,50,20]:',
      '  - button "Go" [ref=e2] [box=0,0,50,20]',
      '- button "Off" [ref=e3] [box=100,100,20,21]',
      '',
    ].join('\n');
    const { entries } = boxJoin(yaml, [
      { tag: 'button', id: 'inner', box: [0, 0, 50, 20] },
      { tag: 'a', href: '/go', id: 'outer', box: [0, 0, 50, 20] },
      { tag: 'button', id: 'off', box: [101, 100, 20, 20] },
    ]);
    expect(entries.map((e) => e.selector)).toEqual(['#outer', '#inner', '#off']);
  });

  it('joins iframe nodes against walk.frames[seq], not by the ref prefix — a navigated main frame has f-refs too', () => {
    const yaml = [
      '- generic [ref=f4e1] [box=0,0,100,100]:',
      '  - button "Main" [ref=f4e2] [box=0,0,10,10]',
      '  - iframe [ref=f4e3] [box=0,20,80,80]:',
      '    - generic [ref=f5e1] [box=0,0,80,80]:',
      '      - button "Child" [ref=f5e2] [box=0,0,10,10]',
      '',
    ].join('\n');
    const { entries, matched } = boxJoin(yaml, {
      main: [{ tag: 'button', id: 'main', box: [0, 0, 10, 10] }],
      frames: { 5: [{ tag: 'button', id: 'child', box: [0, 0, 10, 10] }] },
    });
    expect(matched).toBe(2);
    expect(entries.map((e) => [e.ref, e.selector])).toEqual([
      ['f4e2', '#main'],
      ['f5e2', '#child'],
    ]);
    // Without the frame walk the child line is still in the sidecar, just without a selector.
    const plain = boxJoin(yaml, [{ tag: 'button', id: 'main', box: [0, 0, 10, 10] }]);
    expect(plain.entries.find((e) => e.ref === 'f5e2')?.selector).toBeUndefined();
  });
});

describe('locatorFor / locatorForElement / walkInteractive', () => {
  it('locatorFor and the in-page locatorForElement agree on the same element', () => {
    const doc = { querySelectorAll: () => [1] };
    const element = (/** @type {Record<string, string>} */ attrs, tag = 'button', extra = {}) => ({
      tagName: tag.toUpperCase(),
      id: attrs.id ?? '',
      ownerDocument: doc,
      getAttribute: (/** @type {string} */ n) => attrs[n] ?? null,
      innerText: attrs.__text ?? '',
      placeholder: attrs.placeholder ?? '',
      type: attrs.type ?? '',
      ...extra,
    });
    expect(locatorForElement(/** @type {any} */ (element({ 'data-testid': 'x' })))).toBe('[data-testid="x"]');
    expect(locatorFor({ testid: 'x' })).toBe('[data-testid="x"]');
    expect(locatorForElement(/** @type {any} */ (element({ id: 'first-name' }, 'input')))).toBe('#first-name');
    expect(locatorFor({ id: 'first-name' })).toBe('#first-name');
    expect(locatorForElement(/** @type {any} */ (element({ id: '1st' })))).toBe('[id="1st"]');
    expect(locatorFor({ id: '1st' })).toBe('[id="1st"]');
    expect(locatorForElement(/** @type {any} */ (element({ name: 'city' }, 'input')))).toBe('[name="city"]');
    expect(locatorFor({ nameAttr: 'city' })).toBe('[name="city"]');
    expect(locatorForElement(/** @type {any} */ (element({ href: '/cart' }, 'a')))).toBe('a[href="/cart"]');
    expect(locatorFor({ tag: 'a', href: '/cart' })).toBe('a[href="/cart"]');
    expect(locatorForElement(/** @type {any} */ (element({ __text: 'Do koszyka' })))).toBe(
      'role=button[name="Do koszyka"]',
    );
    expect(locatorFor({ tag: 'button', label: 'Do koszyka' })).toBe('role=button[name="Do koszyka"]');
    expect(locatorFor({ role: 'switch', name: 'Tryb "ciemny"' })).toBe('role=switch[name="Tryb \\"ciemny\\""]');
    expect(locatorFor({ tag: 'div' })).toBeUndefined();
    // Non-unique attributes fall through, in both variants.
    const dup = { querySelectorAll: (/** @type {string} */ s) => (s.startsWith('[data-testid') ? [1, 2] : [1]) };
    expect(
      locatorForElement(
        /** @type {any} */ (
          element({ 'data-testid': 'nav', __text: 'Katalog' }, 'a', {
            ownerDocument: dup,
            getAttribute: (/** @type {string} */ n) => ({ 'data-testid': 'nav', href: '/' })[n] ?? null,
          })
        ),
      ),
    ).toBe('a[href="/"]');
    const unique = uniqueIn([
      { tag: 'a', testid: 'nav', href: '/', box: [0, 0, 1, 1] },
      { tag: 'a', testid: 'nav', href: '/', box: [0, 0, 1, 1] },
      { tag: 'a', testid: 'solo', href: '/new', box: [0, 0, 1, 1] },
    ]);
    expect(locatorFor({ tag: 'a', testid: 'solo', href: '/new', label: 'Nowości' }, unique)).toBe(
      '[data-testid="solo"]',
    );
    // Both the shared testid and the shared href are rejected; the accessible name is what is left.
    expect(locatorFor({ tag: 'a', testid: 'nav', href: '/', label: 'Katalog' }, unique)).toBe(
      'role=link[name="Katalog"]',
    );
  });

  it('maps tags and input types to the roles the aria tree uses', () => {
    expect(implicitRole({ tag: 'a', href: '/', box: [] })).toBe('link');
    expect(implicitRole({ tag: 'a', box: [] })).toBe('generic');
    expect(implicitRole({ tag: 'input', type: 'checkbox', box: [] })).toBe('checkbox');
    expect(implicitRole({ tag: 'input', type: 'search', box: [] })).toBe('searchbox');
    expect(implicitRole({ tag: 'input', type: 'submit', box: [] })).toBe('button');
    expect(implicitRole({ tag: 'input', type: 'password', box: [] })).toBe('textbox');
    expect(implicitRole({ tag: 'select', box: [] })).toBe('combobox');
    expect(implicitRole({ tag: 'div', role: 'tab', box: [] })).toBe('tab');
  });

  it('walkInteractive is self-contained (serialisable into the page) and the real walk has the expected shape', () => {
    const source = walkInteractive.toString();
    expect(source).not.toMatch(/\b(INTERACTIVE_ROLES|implicitRole|locatorFor|escapeAttr)\b/u);
    expect(locatorForElement.toString()).not.toMatch(/\b(implicitRole|escapeAttr|INTERACTIVE_ROLES)\b/u);
    expect(walk.length).toBeGreaterThan(136);
    for (const entry of walk) {
      expect(entry.tag).toMatch(/^[a-z][a-z0-9-]*$/u);
      expect(entry.box).toHaveLength(4);
      expect(entry.box.every(Number.isInteger)).toBe(true);
    }
    expect(walk.filter((e) => e.testid === 'card-add-to-cart').length).toBe(33);
  });
});

describe('findInSnapshot — ≤ 10 lines from the full tree', () => {
  it('finds by name, case-insensitively, capped at 10 with the total', () => {
    const { lines, total } = findInSnapshot(bookstore, 'KOSZYK', { sidecar });
    expect(lines.length).toBe(FIND_MAX);
    expect(total).toBe(34);
    expect(lines[0]).toBe('e45 button "Otwórz koszyk" [data-testid=header-cart-button]');
    expect(lines[1]).toBe('e221 button "add_shopping_cart Do koszyka"');
  });

  it('matches text leaves and climbs to the visible ancestor; a match without one gets its own line', () => {
    expect(findInSnapshot(bookstore, 'Do koszyka').lines[0]).toMatch(/^e221 button /u);
    expect(findInSnapshot(bookstore, 'rowling')).toEqual({ lines: ['e208 generic "J.K. Rowling · 1997"'], total: 1 });
    expect(findInSnapshot(bookstore, 'Tytuł, autor').lines).toEqual(
      ['e79 textbox "Szukaj" [data-testid=filter-query]'].map((l) => l.replace(' [data-testid=filter-query]', '')),
    );
    expect(findInSnapshot(bookstore, '/promotions').lines).toEqual(['e23 link "Promocje" → /promotions']);
    expect(findInSnapshot(bookstore, '')).toEqual({ lines: [], total: 0 });
    expect(findInSnapshot(bookstore, 'nie ma takiego tekstu')).toEqual({ lines: [], total: 0 });
  });

  it('honours max and names', () => {
    const { lines } = findInSnapshot(bookstore, 'Fantasy', { max: 2, names: true });
    expect(lines.length).toBe(2);
    expect(lines[0]).toBe('e107 checkbox "Fantasy" (Gatunek)');
  });
});

describe('--names: container context only when asked, ≤ 60 chars', () => {
  it('appends the nearest region/listitem/article label in parentheses', () => {
    const named = compactLines(bookstore, { sidecar, names: true, fold: false });
    expect(named).toContain('e95 checkbox "Literatura" #mat-mdc-checkbox-1-input (Gatunek)');
    expect(named).toContain('e15 link "Katalog" → /');
    expect(compact.some((l) => /\(Gatunek\)$/u.test(l))).toBe(false);
    const steps = compactLines(wizard, { names: true });
    expect(steps).toContain('f1e13 listitem "Otwórz krok 1: Dane firmy"');
  });

  it('uses the container name, else its first heading, else its first named link/img; cut at 60', () => {
    const long = 'Bardzo długi tytuł artykułu, który zdecydowanie przekracza sześćdziesiąt znaków limitu';
    const yaml = [
      '- list [ref=e1]:',
      `  - listitem [ref=e2]:`,
      `    - heading "${long}" [level=3] [ref=e3]`,
      '    - button "Kup" [ref=e4]',
      '  - listitem [ref=e5]:',
      '    - link "Tytuł" [ref=e6] [cursor=pointer]:',
      '      - /url: /x',
      '    - button "Kup" [ref=e7]',
      '  - listitem [ref=e8]:',
      '    - button "Kup" [ref=e9]',
      '  - article "Sekcja" [ref=e10]:',
      '    - region "Wewnętrzna" [ref=e11]:',
      '      - button "Kup" [ref=e12]',
      '',
    ].join('\n');
    const nodes = parseSnapshot(yaml);
    const byRef = (/** @type {string} */ r) =>
      /** @type {import('../src/snapshot.mjs').SnapNode} */ (nodes.find((n) => n.ref === r));
    const cut = namesContext(nodes, byRef('e4'));
    expect(cut?.length).toBe(60);
    expect(cut?.endsWith('…')).toBe(true);
    expect(namesContext(nodes, byRef('e6'))).toBeUndefined(); // its own name must not label its container
    expect(namesContext(nodes, byRef('e7'))).toBe('Tytuł');
    expect(namesContext(nodes, byRef('e9'))).toBeUndefined();
    expect(namesContext(nodes, byRef('e12'))).toBe('Wewnętrzna');
    expect(CONTEXT_ROLES.has('listitem')).toBe(true);
    // textUnder collects text (inline values and leaves), never names — a heading's name is not text.
    expect(textUnder(nodes, byRef('e2'))).toBe('');
    const shop = parseSnapshot(bookstore);
    const addToCart = /** @type {import('../src/snapshot.mjs').SnapNode} */ (shop.find((n) => n.ref === 'e221'));
    expect(textUnder(shop, addToCart)).toBe('add_shopping_cart Do koszyka');
    expect(textUnder(shop, addToCart, 10)).toBe('add_shopp…');
  });
});

describe('diffSnapshot and aroundRef', () => {
  it('reports added and removed compact lines — a re-labelled button is one of each', () => {
    const before = ['e5 button "Dodaj do koszyka" [data-testid=card-add-to-cart]', 'e6 status: 0'];
    const after = ['e7 button "W koszyku" [data-testid=card-add-to-cart]', 'e6 status: 1'];
    expect(diffSnapshot(before, after)).toEqual({
      added: ['e7 button "W koszyku" [data-testid=card-add-to-cart]', 'e6 status: 1'],
      removed: ['e5 button "Dodaj do koszyka" [data-testid=card-add-to-cart]', 'e6 status: 0'],
    });
    expect(diffSnapshot(before.join('\n'), `${before.join('\n')}\n`)).toEqual({ added: [], removed: [] });
    expect(diffSnapshot(compactSnapshot(bookstore), compactSnapshot(bookstore))).toEqual({ added: [], removed: [] });
  });

  it('aroundRef returns the unfolded neighbourhood, empty for an unknown ref', () => {
    const around = aroundRef(bookstore, 'e221', { sidecar, n: 2 });
    expect(around).toEqual([
      'e199 img "Bloomsbury Harry Potter and the Philosopher\'s Stone"',
      'e207 link "Harry Potter and the Philosopher\'s Stone" → /book/book-013',
      'e221 button "add_shopping_cart Do koszyka"',
      'e228 link → /book/book-009',
      'e230 img "HarperCollins The Lord of the Rings"',
    ]);
    // e253 is behind the fold in the compact view but around still reaches it.
    expect(aroundRef(bookstore, 'e253', { n: 0 })).toEqual(['e253 button "add_shopping_cart Do koszyka"']);
    expect(aroundRef(bookstore, 'e9999')).toEqual([]);
  });
});

describe('resolveRef — aria-ref=<ref> literally, count() precheck, ONE full-page snapshot, fail fast', () => {
  /**
   * @param {number[]} counts  Successive `count()` results.
   */
  const fakePage = (counts) => {
    /** @type {string[]} */
    const calls = [];
    /** @type {any[]} */
    const snapshotArgs = [];
    const queue = [...counts];
    const page = {
      locator: (/** @type {string} */ selector) => {
        calls.push(`locator:${selector}`);
        return {
          count: async () => {
            calls.push('count');
            return queue.shift() ?? 0;
          },
          first: () => {
            throw new Error('unused');
          },
          innerText: async () => '',
          evaluate: async () => undefined,
          ariaSnapshot: async () => {
            throw new Error('subtree snapshot — forbidden');
          },
        };
      },
      ariaSnapshot: async (/** @type {any} */ options) => {
        calls.push('ariaSnapshot');
        snapshotArgs.push(options);
        return '- button "X" [ref=e12]\n';
      },
    };
    return { page: /** @type {any} */ (page), calls, snapshotArgs };
  };

  it('returns the selector without a snapshot when the ref resolves', async () => {
    const { page, calls } = fakePage([1]);
    await expect(resolveRef(page, 'e12')).resolves.toEqual({ selector: 'aria-ref=e12', refreshed: false });
    expect(calls).toEqual(['locator:aria-ref=e12', 'count']);
  });

  it('passes f3e7 through literally — the engine routes the frame', async () => {
    const { page, calls } = fakePage([1]);
    await expect(resolveRef(page, 'f3e7')).resolves.toEqual({ selector: 'aria-ref=f3e7', refreshed: false });
    expect(calls[0]).toBe('locator:aria-ref=f3e7');
  });

  it('refreshes the ref map with ONE full-page ai snapshot (boxes by default) and retries once', async () => {
    const { page, calls, snapshotArgs } = fakePage([0, 1]);
    const result = await resolveRef(page, 'e12');
    expect(result).toEqual({ selector: 'aria-ref=e12', refreshed: true, snapshot: '- button "X" [ref=e12]\n' });
    expect(calls).toEqual(['locator:aria-ref=e12', 'count', 'ariaSnapshot', 'count']);
    expect(snapshotArgs).toEqual([{ mode: 'ai', boxes: true }]);
    const plain = fakePage([0, 1]);
    await resolveRef(plain.page, 'e12', { boxes: false });
    expect(plain.snapshotArgs).toEqual([{ mode: 'ai', boxes: false }]);
  });

  it('fails immediately with the DESIGN.md reason when the ref is still gone — no waiting', async () => {
    const { page, calls } = fakePage([0, 0]);
    const started = Date.now();
    const error = await resolveRef(page, 'e99').catch((e) => e);
    expect(Date.now() - started).toBeLessThan(100);
    expect(error).toBeInstanceOf(RefNotFoundError);
    expect(error.message).toBe(REF_NOT_FOUND);
    expect(error).toMatchObject({ code: 'E_REF_NOT_FOUND', ref: 'e99' });
    expect(calls).toEqual(['locator:aria-ref=e99', 'count', 'ariaSnapshot', 'count']);
  });

  it('rejects a malformed ref before touching the page', async () => {
    const { page, calls } = fakePage([1]);
    await expect(resolveRef(page, 'button')).rejects.toBeInstanceOf(RefNotFoundError);
    expect(calls).toEqual([]);
  });
});

describe('engine-facing helpers: entries alias, sidecarFromPage, snapshotArtifacts', () => {
  it('accepts { entries } as the sidecar — the name the engine passes to snapshotTools.compact', () => {
    expect(compactLines(bookstore, { entries: sidecar })).toEqual(compact);
    expect(findInSnapshot(bookstore, 'koszyk', { entries: sidecar }).lines[0]).toBe(
      'e45 button "Otwórz koszyk" [data-testid=header-cart-button]',
    );
  });

  it('sidecarFromPage walks the main frame and each iframe in order, never calling ariaSnapshot', async () => {
    const yaml = [
      '- generic [ref=e1] [box=0,0,100,100]:',
      '  - button "Main" [ref=e2] [box=0,0,10,10]',
      '  - iframe [ref=e3] [box=0,20,80,80]:',
      '    - generic [ref=f1e1] [box=0,0,80,80]:',
      '      - button "Child" [ref=f1e2] [box=0,0,10,10]',
      '  - iframe [ref=e4] [box=0,20,80,80]',
      '  - iframe [ref=e5] [box=0,20,80,80]:',
      '    - generic [ref=f3e1] [box=0,0,80,80]:',
      '      - button "Cross" [ref=f3e2] [box=0,0,10,10]',
      '',
    ].join('\n');
    /** @type {string[]} */
    const calls = [];
    const frame = (/** @type {string} */ name, /** @type {any} */ result) => ({
      url: () => name,
      locator: () => {
        throw new Error('unused');
      },
      evaluate: async (/** @type {any} */ fn) => {
        calls.push(`${name}:${fn === walkInteractive ? 'walkInteractive' : 'other'}`);
        if (result instanceof Error) throw result;
        return result;
      },
    });
    const page = /** @type {any} */ ({
      evaluate: async (/** @type {any} */ fn) => {
        calls.push(`main:${fn === walkInteractive ? 'walkInteractive' : 'other'}`);
        return [{ tag: 'button', id: 'main', box: [0, 0, 10, 10] }];
      },
      ariaSnapshot: async () => {
        throw new Error('sidecarFromPage must not snapshot');
      },
      frames: () => [
        frame('top', null),
        frame('child', [{ tag: 'button', id: 'child', box: [0, 0, 10, 10] }]),
        frame('cross', new Error('cross-origin')),
      ],
    });
    const entries = await sidecarFromPage(page, yaml);
    expect(calls).toEqual(['main:walkInteractive', 'child:walkInteractive', 'cross:walkInteractive']);
    expect(entries.map((e) => [e.ref, e.selector])).toEqual([
      ['e2', '#main'],
      ['f1e2', '#child'],
      ['f3e2', undefined],
    ]);
    // A page without frames() is fine too (a FakePage of another package).
    const bare = await sidecarFromPage(/** @type {any} */ ({ evaluate: async () => [] }), yaml);
    expect(bare.map((e) => e.ref)).toEqual(['e2', 'f1e2', 'f3e2']);
  });

  it('snapshotArtifacts masks secrets everywhere and drops sensitive values from full, md and json', () => {
    const yaml = [
      '- generic [ref=e1] [box=0,0,300,100]:',
      '  - textbox "E-mail" [ref=e2] [box=0,0,100,20]: jan@example.com',
      '  - textbox "Hasło" [ref=e3] [box=0,20,100,20]: tajne',
      '  - textbox "Kod" [ref=e4] [box=0,40,100,20]: 123456',
      '  - button "Zaloguj" [ref=e5] [box=0,60,100,20]',
      '',
    ].join('\n');
    const { entries } = boxJoin(yaml, [
      { tag: 'input', type: 'email', nameAttr: 'email', box: [0, 0, 100, 20] },
      { tag: 'input', type: 'password', nameAttr: 'password', sensitive: true, box: [0, 20, 100, 20] },
      { tag: 'input', type: 'text', nameAttr: 'otp', sensitive: true, box: [0, 40, 100, 20] },
      { tag: 'button', testid: 'login', box: [0, 60, 100, 20] },
    ]);
    const out = snapshotArtifacts(yaml, entries, { secretValues: ['jan@example.com'] });
    expect(out.sensitive).toEqual(['e3', 'e4']);
    expect(out.md).toBe(
      [
        'e2 textbox "E-mail" [name=email] = ***',
        'e3 textbox "Hasło" [name=password]',
        'e4 textbox "Kod" [name=otp]',
        'e5 button "Zaloguj" [data-testid=login]',
        '',
      ].join('\n'),
    );
    expect(out.full).not.toMatch(/tajne|123456|jan@example\.com/u);
    expect(out.full).toContain('[ref=e2] [box=0,0,100,20]: ***');
    expect(out.full).toContain('[ref=e3] [box=0,20,100,20]\n');
    expect(JSON.stringify(out.entries)).not.toMatch(/tajne|123456|jan@example/u);
    expect(out.entries.find((e) => e.ref === 'e3')).toMatchObject({ sensitive: true, selector: '[name="password"]' });
    // The inputs are untouched (pure function, new objects).
    expect(entries.find((e) => e.ref === 'e3')?.sensitive).toBe(true);
    expect(yaml).toContain('tajne');
  });

  it('a label with a colon — the usual Polish form — does not smuggle the value past the mask', () => {
    // `textbox "Hasło:"` leaves the key bare; `"Kod: SMS"` makes the renderer quote the whole key.
    const yaml = [
      '- generic [ref=e1] [box=0,0,300,100]:',
      '  - textbox "Hasło:" [ref=e2] [box=0,0,100,20]: tajne',
      `  - 'textbox "Kod: SMS" [ref=e3] [box=0,20,100,20]': "123456"`,
      '',
    ].join('\n');
    const { entries } = boxJoin(yaml, [
      { tag: 'input', type: 'password', nameAttr: 'password', sensitive: true, box: [0, 0, 100, 20] },
      { tag: 'input', type: 'text', nameAttr: 'otp', sensitive: true, box: [0, 20, 100, 20] },
    ]);
    const out = snapshotArtifacts(yaml, entries);
    expect(out.sensitive).toEqual(['e2', 'e3']);
    expect(out.full).not.toMatch(/tajne|123456/u);
    expect(out.md).not.toMatch(/tajne|123456/u);
    // The quoted key keeps its quotes — the file stays valid YAML.
    expect(out.full).toContain(`- 'textbox "Kod: SMS" [ref=e3] [box=0,20,100,20]'\n`);
  });
});
