// CODE-INDEX.md — the repository's dependency index, for LLM-driven development.
//
// One cheap file answers "what does module X export" and "who depends on it" without grepping the
// tree: an agent reads the index first and opens only the files that matter, which is faster and
// cheaper than a full-tree scan. It covers the TOOLING (tools/scripts, tools/hooks, the vendored
// browser-inspector and the ALM integrations of tools/alm) and the PUBLIC API of the workspace
// (every library's `public-api.ts`, every application's `app.routes.ts`) — the map level. Questions
// below that level are answered by opening the file the index names, not by indexing everything.
//
// Regenerated by the pre-commit hook (`.githooks/pre-commit`, armed by `npm run prepare`) and
// guarded by `npm run verify` — a stale index fails the gate instead of silently drifting.
//
// Regex-based ON PURPOSE, not an AST: the repository's export style is uniform
// (`export [async] function|const|let|class NAME`, plus the occasional `export { a, b }`), a
// wrong line in an index is a cosmetic bug rather than a runtime one, and a parser would be a
// dependency taken on for a documentation file.
import { existsSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import os from 'node:os';
import path from 'node:path';
import { REPO, isMain } from './lib/repo.mjs';
import { skipDirectory } from './lib/scan.mjs';

export const INDEX_FILE = 'CODE-INDEX.md';

/**
 * Directories walked for source files, relative to the repository root — the tooling in full. Tests,
 * fixtures and build output are deliberately not modules of the dependency map.
 */
const TOOL_DIRS = [
  'tools/scripts',
  'tools/hooks',
  'tools/testing',
  'tools/browser-inspector/bin',
  'tools/browser-inspector/src',
  'tools/alm/scripts',
  'tools/alm/integrations',
];
/** Public-API files of workspace projects: the map level of applications and libraries. */
const PUBLIC_API =
  /^(?:libs\/.*\/src\/public-api\.ts|libs\/.*\/src\/index\.ts|apps\/[^/]+\/src\/app\/app\.routes\.ts)$/u;
/**
 * This script's OWN policy, on top of the shared rule in lib/scan.mjs: a directory of tests,
 * fixtures, templates or examples is not a MODULE of the dependency map, whatever depth it sits at.
 * That is a decision about what the index is for, not a claim about what those directories are —
 * which is why it lives here and not in the shared list.
 */
const NOT_A_MODULE = Object.freeze(['fixtures', 'test', 'templates', 'examples']);

/**
 * Declaration names from `export [async] function|const|let|class NAME` and the names in
 * `export { a, b as c }` (the exported name, after `as`). Sorted, deduplicated.
 * @param {string} source
 * @returns {string[]}
 */
export function parseExports(source) {
  const names = new Set();
  const declaration =
    /^export\s+(?:async |abstract )?(?:function\s*\*?|const|let|var|class|interface|type|enum)\s+([\w$]+)/gmu;
  for (const match of source.matchAll(declaration)) names.add(match[1]);
  // `export { x }` lists — but not re-exports (`export { x } from` another module), which belong to
  // the module they come from; the negative lookahead keeps them out. Comments are not stripped
  // (regex, not a parser), so a source comment must not spell out an import specifier literally.
  const list = /^export\s*\{([^}]*)\}(?!\s*from)/gmu;
  for (const match of source.matchAll(list)) {
    for (const item of match[1].split(',')) {
      const name = item
        .trim()
        .split(/\s+as\s+/u)
        .pop()
        ?.trim();
      if (name) names.add(name);
    }
  }
  return [...names].sort();
}

/**
 * The source with block comments blanked out, newlines kept so nothing shifts line-wise. Parsing
 * imports and environment reads out of a file that documents both in its own comments otherwise
 * reports the documentation as code — `@typedef {import('./types.js').X}` is a TYPE edge, and
 * a `BROWSER_INSPECTOR_*` name quoted in an error message is not a read.
 * @param {string} source
 * @returns {string}
 */
export function stripBlockComments(source) {
  // Whole-line `//` comments go first: a header that mentions `tools/testing/**` would otherwise open
  // a block comment that never closes where the author meant and swallow the imports below it.
  // Both kinds are blanked, not cut, so line numbers stay put.
  const blank = (/** @type {string} */ text) => text.replaceAll(/[^\n]/gu, ' ');
  return source.replaceAll(/^\s*\/\/.*$/gmu, blank).replaceAll(/\/\*[\s\S]*?\*\//gu, blank);
}

/**
 * What the module is FOR, in the author's own words: the first comment line of the file, minus the
 * `name.mjs — ` prefix that the section heading already carries. Written by a human and present in
 * most modules here, so this costs nothing to author and answers the question that
 * decides everything else — open this file or not.
 * @param {string} source
 * @returns {string} empty when the file opens without a comment
 */
export function parsePurpose(source) {
  /** @type {string[]} */
  const paragraph = [];
  let inBlock = false;
  for (const raw of source.split('\n')) {
    const line = raw.trim();
    if (!inBlock && paragraph.length === 0 && (line === '' || line.startsWith('#!'))) continue;
    /** @type {string | null} */
    let text = null;
    if (line.startsWith('//')) text = line.slice(2).trim();
    else if (line.startsWith('/*')) {
      inBlock = true;
      text = line
        .replace(/^\/\*+/u, '')
        .replace(/\*\/$/u, '')
        .trim();
    } else if (inBlock && line.startsWith('*'))
      text = line
        .replace(/^\*+\/?/u, '')
        .replace(/\*\/$/u, '')
        .trim();
    if (text === null) break;
    // The header's first PARAGRAPH: an empty comment line ends it once something was collected.
    // Taking one physical line instead cut every wrapped header mid-sentence.
    if (text === '') {
      if (paragraph.length > 0) break;
    } else {
      paragraph.push(text);
    }
    if (inBlock && line.endsWith('*/')) break;
  }
  if (paragraph.length === 0) return '';
  const joined = paragraph.join(' ').replace(/\s+/gu, ' ').trim();
  const dash = /^\S+\s+—\s+(.*)$/u.exec(joined);
  const body = (dash ? dash[1] : joined).trim();
  // Cut on ". " rather than on "." so `types.d.ts` and `§2.2` do not end the sentence early.
  const stop = body.indexOf('. ');
  const sentence = stop === -1 ? body : body.slice(0, stop + 1);
  return sentence.length > PURPOSE_CAP ? `${sentence.slice(0, PURPOSE_CAP - 1)}…` : sentence;
}

/**
 * Environment variables the module READS, in the three shapes this tree uses: `env.NAME`,
 * `env['NAME']` and a helper that takes the env object and the name (`intEnv(env, 'NAME', …)`).
 * A knob is a contract exactly like an event subscription and is just as invisible in an import
 * list. A name read some fourth way is a missing row, never a wrong one — the same bargain the
 * rest of this file makes by being a regex.
 * @param {string} source
 * @returns {string[]} sorted, deduplicated
 */
export function parseEnvKnobs(source) {
  const code = stripBlockComments(source);
  const out = new Set();
  const patterns = [
    /(?:process\.)?env\.([A-Z][A-Z0-9_]{2,})\b/gu,
    /(?:process\.)?env\[\s*['"]([A-Z][A-Z0-9_]{2,})['"]\s*\]/gu,
    /\(\s*env\s*,\s*['"]([A-Z][A-Z0-9_]{2,})['"]/gu,
  ];
  for (const pattern of patterns) {
    for (const match of code.matchAll(pattern)) out.add(match[1]);
  }
  return [...out].sort();
}

/**
 * TYPE-ONLY dependencies: `import('./x.js')` written inside a JSDoc comment. They used to be
 * reported as ordinary imports, which was wrong twice over — the edge does not exist at runtime,
 * and the specifier `./types.js` names a file that is not on disk (the declarations live in
 * `types.d.ts`, which TypeScript resolves on its own). An agent following that edge opened
 * nothing. Reported separately and resolved to the file that EXISTS by the caller.
 * @param {string} source
 * @param {string} fromFile repository-relative POSIX path of the importing file
 * @returns {string[]}
 */
export function parseTypeImports(source, fromFile) {
  const out = new Set();
  for (const block of source.matchAll(/\/\*[\s\S]*?\*\//gu)) {
    // Prose quotes examples in backticks (`import('./x.js')`); an annotation never sits inside one.
    const annotations = block[0].replaceAll(/`[^`\n]*`/gu, '');
    for (const match of annotations.matchAll(/\bimport\s*\(\s*['"](\.[^'"]+)['"]\s*\)/gu)) {
      out.add(path.posix.join(path.posix.dirname(fromFile), match[1]));
    }
  }
  return [...out].sort();
}

/**
 * Whether `index` lies inside a template literal: an odd number of unescaped backticks precede it.
 * Generated code lives in template literals (a generator's `page.on('console')` is not the
 * generator's own subscription), and this parity test is what a regex-based index can afford.
 * @param {string} code
 * @param {number} index
 * @returns {boolean}
 */
export function insideTemplateLiteral(code, index) {
  let count = 0;
  for (let i = 0; i < index; i += 1) {
    if (code[i] === '`' && code[i - 1] !== '\\') count += 1;
  }
  return count % 2 === 1;
}

/**
 * Whether `index` lies inside a single- or double-quoted string on its line: an odd number of
 * unescaped quotes of one kind precede it. A generator that writes `"import { App } from './app/app';"`
 * as a string is not importing anything.
 * @param {string} code
 * @param {number} index
 * @returns {boolean}
 */
export function insideStringLiteral(code, index) {
  const lineStart = code.lastIndexOf('\n', index) + 1;
  let single = 0;
  let double = 0;
  for (let i = lineStart; i < index; i += 1) {
    if (code[i - 1] === '\\') continue;
    if (code[i] === "'") single += 1;
    else if (code[i] === '"') double += 1;
  }
  return single % 2 === 1 || double % 2 === 1;
}

/**
 * LOCAL import specifiers (`./x.mjs`, `../shared/x.mjs`) from static `import … from` and dynamic
 * `import('…')`, resolved against the importing file into repository-relative POSIX paths.
 * Dynamic imports matter here: the keeper loads the engine lazily so the client never pays for it,
 * and that edge is exactly what a reader of the map wants to see. Package imports are noise for a
 * dependency map of THIS repository and are dropped.
 * @param {string} source
 * @param {string} fromFile repository-relative POSIX path of the importing file
 * @returns {string[]}
 */
export function parseImports(source, fromFile) {
  const out = new Set();
  const code = stripBlockComments(source);
  const patterns = [/\bfrom\s+['"](\.[^'"]+)['"]/gu, /\bimport\s*\(\s*['"](\.[^'"]+)['"]\s*\)/gu];
  for (const pattern of patterns) {
    for (const match of code.matchAll(pattern)) {
      if (match[1].includes('${') || insideTemplateLiteral(code, match.index) || insideStringLiteral(code, match.index))
        continue;
      const resolved = path.posix.join(path.posix.dirname(fromFile), match[1]);
      // TypeScript sources (tools/alm) write `./x.js` (NodeNext) for a file that is `./x.ts` on disk.
      out.add(fromFile.endsWith('.ts') ? resolved.replace(/\.js$/u, '.ts') : resolved);
    }
  }
  return [...out].sort();
}

/**
 * Collapse a parameter list to something readable in one line of an index: whitespace squeezed,
 * a destructured object shown as `{…}` and a default value dropped. `fill(selector, value)` is
 * what a reader needs; the exact default of the third argument is what the file is for.
 * @param {string} raw text between the parentheses of a declaration
 * @returns {string}
 */
export function condenseParams(raw) {
  // Inline type annotations (`/** @type {x} */ value`) are how this repository types a parameter
  // it cannot annotate in the JSDoc block; in a signature they are noise that hides the name.
  const text = raw.replace(/\/\*[\s\S]*?\*\//gu, ' ');
  let depth = 0;
  let out = '';
  for (const ch of text) {
    if (ch === '{' || ch === '[') {
      if (depth === 0) out += ch === '{' ? '{…}' : '[…]';
      depth++;
      continue;
    }
    if (ch === '}' || ch === ']') {
      depth = Math.max(0, depth - 1);
      continue;
    }
    if (depth === 0) out += ch;
  }
  return out
    .replace(/=[^,]*/gu, '')
    .split(',')
    .map((part) => part.trim())
    .filter((part) => part !== '')
    .join(', ');
}

/** How much of a return type earns its place in a one-line index entry before it stops helping. */
const TYPE_CAP = 60;

/** Same idea for the module's one-line purpose: a sentence, not the paragraph the file opens with. */
const PURPOSE_CAP = 140;

/**
 * The `@returns {…}` type of a JSDoc block, with BALANCED braces: an object literal type nests
 * them, and stopping at the first `}` printed half a type and called it a signature. Continuation
 * markers (`\n * `) are folded away, and anything longer than the cap is cut with an ellipsis —
 * the index says which function to open, the file says the rest.
 * @param {string} block one JSDoc comment, from the opening `/**` to the closing star-slash
 * @returns {string} the type, or an empty string when the block declares none
 */
export function returnType(block) {
  const tag = /@returns?\s*\{/u.exec(block);
  if (!tag) return '';
  const open = tag.index + tag[0].length - 1;
  let depth = 0;
  let close = -1;
  for (let i = open; i < block.length; i++) {
    if (block[i] === '{') depth++;
    else if (block[i] === '}') {
      depth--;
      if (depth === 0) {
        close = i;
        break;
      }
    }
  }
  if (close === -1) return '';
  const type = block
    .slice(open + 1, close)
    .replace(/^\s*\*\s?/gmu, ' ')
    .replace(/\s+/gu, ' ')
    .trim();
  return type.length > TYPE_CAP ? `${type.slice(0, TYPE_CAP - 1)}…` : type;
}

/**
 * The INPUT and OUTPUT of every exported function: its parameter names, and the return type when
 * the JSDoc block right above it declares one. This is the half of a symbol a reader actually
 * needs before deciding whether to open the file — a bare name says a function exists, a signature
 * says whether it is the one being looked for.
 *
 * Types come from JSDoc rather than from the code because that is where this repository keeps
 * them (`tsc --checkJs`); a function without `@returns` simply has no arrow, which is honest.
 * @param {string} source
 * @returns {Map<string, string>} exported name → `name(a, b) → Type`
 */
export function parseSignatures(source) {
  /** @type {Map<string, string>} */
  const out = new Map();
  const fn = /^export\s+(?:async\s+)?function\s*\*?\s*([A-Za-z_$][\w$]*)\s*\(/gmu;
  const arrow = /^export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s+)?\(/gmu;
  for (const pattern of [fn, arrow]) {
    for (const match of source.matchAll(pattern)) {
      const open = match.index + match[0].length - 1;
      let depth = 0;
      let close = open;
      for (let i = open; i < source.length; i++) {
        if (source[i] === '(') depth++;
        else if (source[i] === ')') {
          depth--;
          if (depth === 0) {
            close = i;
            break;
          }
        }
      }
      const params = condenseParams(source.slice(open + 1, close));
      // The NEAREST preceding JSDoc block, found by scanning backwards rather than with a regex:
      // a non-greedy `/**…*/` anchored at the declaration matches from the FIRST block in the file
      // and hands back the wrong `@returns` — measured, every symbol in recorder.mjs inherited the
      // return type of the first function above it.
      const before = source.slice(0, match.index).replace(/\s+$/u, '');
      const start = before.endsWith('*/') ? before.lastIndexOf('/**') : -1;
      const type = start === -1 ? '' : returnType(before.slice(start));
      out.set(match[1], `${match[1]}(${params})${type === '' ? '' : ` → ${type}`}`);
    }
  }
  return out;
}

/**
 * What the module SUBSCRIBES TO: `receiver.on('event')`, `.once`, `.addListener`. Event wiring is
 * the part of this codebase that a dependency map otherwise hides — the recorder's whole contract
 * with the page is a list of events, and `keeper.mjs` decides its own lifetime from process
 * signals. Neither is visible in an import list, and both are the first thing a reader looks for.
 * @param {string} source
 * @returns {string[]} `receiver:event`, sorted and deduplicated
 */
export function parseSubscriptions(source) {
  const out = new Set();
  const code = stripBlockComments(source);
  const pattern = /([A-Za-z_$][\w$.]*)\s*\.\s*(?:on|once|addListener)\s*\(\s*['"]([\w:.-]+)['"]/gu;
  for (const match of code.matchAll(pattern)) {
    if (insideTemplateLiteral(code, match.index)) continue;
    const receiver = match[1].split('.').pop() ?? match[1];
    out.add(`${receiver}:${match[2]}`);
  }
  return [...out].sort();
}

/**
 * Walk the source tree: every `.mjs`/`.mts`/`.ts` under the tooling directories, plus the public-API
 * files of workspace projects; tests, declaration files, fixtures, node_modules and builds excluded.
 * @param {string} root absolute repository root
 * @returns {string[]} repository-relative POSIX paths, sorted
 */
export function listSourceFiles(root) {
  /** @type {string[]} */
  const files = [];
  /** @param {string} dir @param {(rel: string) => boolean} accept @param {number} depth */
  const walk = (dir, accept, depth) => {
    const abs = path.join(root, dir);
    if (!existsSync(abs)) return;
    for (const entry of readdirSync(abs, { withFileTypes: true })) {
      const rel = path.posix.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!skipDirectory(entry.name, depth, NOT_A_MODULE)) walk(rel, accept, depth + 1);
        continue;
      }
      if (/\.(?:test|spec)\.(?:mjs|ts)$/u.test(entry.name) || entry.name.endsWith('.d.ts')) continue;
      if (accept(rel)) files.push(rel);
    }
  };
  for (const dir of TOOL_DIRS) walk(dir, (rel) => /\.(?:mjs|mts|ts)$/u.test(rel), 0);
  for (const dir of ['apps', 'libs']) walk(dir, (rel) => PUBLIC_API.test(rel), 0);
  return files.sort();
}

/**
 * The whole index as one deterministic markdown string.
 * @param {{ path: string, purpose?: string, exports: string[], imports: string[], typeImports?: string[], env?: string[], signatures?: Map<string, string>, subscriptions?: string[] }[]} files
 * @returns {string}
 */
export function buildIndex(files) {
  /** @type {Map<string, string[]>} */
  const importedBy = new Map();
  for (const file of files) {
    for (const dep of file.imports) {
      const list = importedBy.get(dep) ?? [];
      list.push(file.path);
      importedBy.set(dep, list);
    }
  }
  const lines = [
    '# CODE-INDEX',
    '',
    'Dependency map of this repository — generated, do not edit by hand.',
    'Regenerate: `npm run code-index` (the pre-commit hook does it on every commit;',
    '`npm run verify` fails when this file is stale). One section per module:',
    'what it is **for**, what it **exports** (with the inputs and output of every function), what it',
    '**subscribes to**, which **environment** knobs it reads, what it **imports** (runtime edges and',
    'type-only edges apart) and **who imports it** — read this before grepping.',
    '',
    `Modules: ${String(files.length)}.`,
    '',
  ];
  for (const file of files) {
    lines.push(`## ${file.path}`);
    if (file.purpose) lines.push(`- purpose: ${file.purpose}`);
    if (file.exports.length > 0) {
      const spell = (/** @type {string} */ name) => `\`${file.signatures?.get(name) ?? name}\``;
      lines.push(`- exports: ${file.exports.map(spell).join(', ')}`);
    }
    if (file.subscriptions && file.subscriptions.length > 0)
      lines.push(`- subscribes: ${file.subscriptions.map((n) => `\`${n}\``).join(', ')}`);
    if (file.env && file.env.length > 0) lines.push(`- env: ${file.env.map((n) => `\`${n}\``).join(', ')}`);
    if (file.imports.length > 0) lines.push(`- imports: ${file.imports.map((n) => `\`${n}\``).join(', ')}`);
    if (file.typeImports && file.typeImports.length > 0)
      lines.push(`- types only: ${file.typeImports.map((n) => `\`${n}\``).join(', ')}`);
    const consumers = (importedBy.get(file.path) ?? []).sort();
    if (consumers.length > 0) lines.push(`- imported by: ${consumers.map((n) => `\`${n}\``).join(', ')}`);
    if (
      !file.purpose &&
      file.exports.length === 0 &&
      file.imports.length === 0 &&
      consumers.length === 0 &&
      (file.subscriptions ?? []).length === 0 &&
      (file.env ?? []).length === 0
    )
      lines.push('- (entrypoint — nothing exported, nothing imported, nothing imports it)');
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * A JSDoc `import('./x.js')` names the specifier TypeScript resolves, not the file on disk: this
 * tree writes `./types.js` and ships `types.d.ts`. Resolve to what exists, and when nothing does,
 * say so in the row rather than printing a path that opens nothing — the failure that made this
 * function necessary.
 * @param {string} root absolute repository root
 * @param {string} spec repository-relative POSIX path from the specifier
 * @returns {string}
 */
export function resolveTypeImport(root, spec) {
  const candidates = [spec, spec.replace(/\.js$/u, '.d.ts'), spec.replace(/\.js$/u, '.ts'), `${spec}.d.ts`];
  for (const candidate of candidates) {
    if (existsSync(path.join(root, candidate))) return candidate;
  }
  return `${spec} (unresolved)`;
}

/**
 * @param {string} root absolute repository root
 * @returns {string}
 */
export function generateIndex(root) {
  const files = listSourceFiles(root).map((rel) => {
    const source = readFileSync(path.join(root, rel), 'utf8');
    return {
      path: rel,
      purpose: parsePurpose(source),
      exports: parseExports(source),
      imports: parseImports(source, rel).map((spec) =>
        existsSync(path.join(root, spec)) ? spec : `${spec} (unresolved)`,
      ),
      typeImports: parseTypeImports(source, rel).map((spec) => resolveTypeImport(root, spec)),
      env: parseEnvKnobs(source),
      signatures: parseSignatures(source),
      subscriptions: parseSubscriptions(source),
    };
  });
  return buildIndex(files);
}

/**
 * The STAGED tree exported to a temporary directory — what the commit will contain, as opposed to the
 * working tree with its half-staged edits. The pre-commit hook indexes this.
 * @returns {string} the directory; the caller removes it
 */
function exportStagedTree() {
  const dir = mkdtempSync(path.join(os.tmpdir(), 'cb-index-staged-'));
  const result = spawnSync('git', ['checkout-index', '-a', '--prefix', `${dir}${path.sep}`], {
    cwd: REPO,
    encoding: 'utf8',
  });
  if (result.status !== 0) throw new Error(`git checkout-index failed: ${result.stderr}`);
  return dir;
}

if (isMain(import.meta.url)) {
  // Always the repository root, whatever the cwd: the hook and the gate call this from anywhere.
  const staged = process.argv.includes('--staged') ? exportStagedTree() : null;
  const fresh = generateIndex(staged ?? REPO);
  if (staged) rmSync(staged, { recursive: true, force: true });
  const target = path.join(REPO, INDEX_FILE);
  if (process.argv.includes('--check')) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current === fresh) {
      process.stdout.write(`${INDEX_FILE} is fresh\n`);
    } else {
      process.stderr.write(
        `${INDEX_FILE} is STALE — run \`npm run code-index\` (the pre-commit hook does this automatically)\n`,
      );
      process.exitCode = 1;
    }
  } else {
    writeFileSync(target, fresh, 'utf8');
    process.stdout.write(`wrote ${INDEX_FILE}\n`);
  }
}
