// CODE-INDEX.md — the repository's dependency index, for LLM-driven development.
//
// One cheap file answers "what does module X export" and "who depends on it" without grepping
// the tree: an agent reads the index first and opens only the files that matter, which is faster
// and cheaper than a full-tree scan. Ported from scribe and adapted to a tree that is plain ESM
// `.mjs` end to end (no `.js` → `.ts` rewriting; specifiers name the file on disk).
//
// Regenerated by the pre-commit hook (`.githooks/pre-commit`, armed by `npm run prepare`) and
// guarded by `npm run verify` — a stale index fails the gate instead of silently drifting.
//
// Regex-based ON PURPOSE, not an AST: the repository's export style is uniform
// (`export [async] function|const|let|class NAME`, plus the occasional `export { a, b }`), a
// wrong line in an index is a cosmetic bug rather than a runtime one, and a parser would be a
// dependency taken on for a documentation file.
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const INDEX_FILE = 'CODE-INDEX.md';

/**
 * Directories walked for source files, relative to the repository root. `packages/<name>/src`
 * and `packages/<name>/bin` are the product, `scripts` the tooling, `bench` the harness — tests,
 * fixtures, probes and committed builds are deliberately not modules of the dependency map.
 */
const PACKAGE_SUBDIRS = ['src', 'bin'];
const TOP_LEVEL = ['scripts', 'bench'];
const SKIP_DIRS = new Set(['node_modules', 'dist', 'fixtures', 'test', 'probes', 'app', 'out', 'templates']);

/**
 * Declaration names from `export [async] function|const|let|class NAME` and the names in
 * `export { a, b as c }` (the exported name, after `as`). Sorted, deduplicated.
 * @param {string} source
 * @returns {string[]}
 */
export function parseExports(source) {
  const names = new Set();
  const declaration = /^export\s+(?:async\s+)?(?:function\s*\*?|const|let|var|class)\s+([A-Za-z_$][\w$]*)/gmu;
  for (const match of source.matchAll(declaration)) names.add(match[1]);
  // `export { x }` lists — but not re-exports (`export { x } from` another module), which belong to
  // the module they come from; the negative lookahead keeps them out. Comments are not stripped
  // (regex, not a parser), so a source comment must not spell out an import specifier literally.
  const list = /^export\s*\{([^}]*)\}(?!\s*from)/gmu;
  for (const match of source.matchAll(list)) {
    for (const item of match[1].split(',')) {
      const name = item
        .trim()
        .split(/\s+as\s+/u)
        .pop()
        ?.trim();
      if (name) names.add(name);
    }
  }
  return [...names].sort();
}

/**
 * LOCAL import specifiers (`./x.mjs`, `../shared/x.mjs`) from static `import … from` and dynamic
 * `import('…')`, resolved against the importing file into repository-relative POSIX paths.
 * Dynamic imports matter here: the keeper loads the engine lazily so the client never pays for it,
 * and that edge is exactly what a reader of the map wants to see. Package imports are noise for a
 * dependency map of THIS repository and are dropped.
 * @param {string} source
 * @param {string} fromFile repository-relative POSIX path of the importing file
 * @returns {string[]}
 */
export function parseImports(source, fromFile) {
  const out = new Set();
  const patterns = [/\bfrom\s+['"](\.[^'"]+)['"]/gu, /\bimport\s*\(\s*['"](\.[^'"]+)['"]\s*\)/gu];
  for (const pattern of patterns) {
    for (const match of source.matchAll(pattern)) {
      out.add(path.posix.join(path.posix.dirname(fromFile), match[1]));
    }
  }
  return [...out].sort();
}

/**
 * Walk the source tree: every `.mjs` under `packages/<name>/{src,bin}`, `scripts` and `bench`;
 * tests (`*.test.mjs`, `*.spec.mjs`), fixtures, probes, node_modules and builds excluded.
 * @param {string} root absolute repository root
 * @returns {string[]} repository-relative POSIX paths, sorted
 */
export function listSourceFiles(root) {
  /** @type {string[]} */
  const files = [];
  /** @param {string} dir */
  const walk = (dir) => {
    const abs = path.join(root, dir);
    if (!existsSync(abs)) return;
    for (const entry of readdirSync(abs, { withFileTypes: true })) {
      const rel = path.posix.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (!SKIP_DIRS.has(entry.name)) walk(rel);
        continue;
      }
      if (!entry.name.endsWith('.mjs')) continue;
      if (/\.(?:test|spec)\.mjs$/u.test(entry.name)) continue;
      files.push(rel);
    }
  };
  const packagesDir = path.join(root, 'packages');
  if (existsSync(packagesDir)) {
    for (const pkg of readdirSync(packagesDir, { withFileTypes: true })) {
      if (!pkg.isDirectory()) continue;
      for (const sub of PACKAGE_SUBDIRS) walk(path.posix.join('packages', pkg.name, sub));
    }
  }
  for (const dir of TOP_LEVEL) walk(dir);
  return files.sort();
}

/**
 * The whole index as one deterministic markdown string.
 * @param {{ path: string, exports: string[], imports: string[] }[]} files
 * @returns {string}
 */
export function buildIndex(files) {
  /** @type {Map<string, string[]>} */
  const importedBy = new Map();
  for (const file of files) {
    for (const dep of file.imports) {
      const list = importedBy.get(dep) ?? [];
      list.push(file.path);
      importedBy.set(dep, list);
    }
  }
  const lines = [
    '# CODE-INDEX',
    '',
    'Dependency map of this repository — generated, do not edit by hand.',
    'Regenerate: `npm run code-index` (the pre-commit hook does it on every commit;',
    '`npm run verify` fails when this file is stale). One section per module:',
    'what it **exports**, what it **imports** and **who imports it** — read this before grepping.',
    '',
    `Modules: ${String(files.length)}.`,
    '',
  ];
  for (const file of files) {
    lines.push(`## ${file.path}`);
    if (file.exports.length > 0) lines.push(`- exports: ${file.exports.map((n) => `\`${n}\``).join(', ')}`);
    if (file.imports.length > 0) lines.push(`- imports: ${file.imports.map((n) => `\`${n}\``).join(', ')}`);
    const consumers = (importedBy.get(file.path) ?? []).sort();
    if (consumers.length > 0) lines.push(`- imported by: ${consumers.map((n) => `\`${n}\``).join(', ')}`);
    if (file.exports.length === 0 && file.imports.length === 0 && consumers.length === 0)
      lines.push('- (entrypoint — nothing exported, nothing imported, nothing imports it)');
    lines.push('');
  }
  return lines.join('\n');
}

/**
 * @param {string} root absolute repository root
 * @returns {string}
 */
export function generateIndex(root) {
  const files = listSourceFiles(root).map((rel) => {
    const source = readFileSync(path.join(root, rel), 'utf8');
    return { path: rel, exports: parseExports(source), imports: parseImports(source, rel) };
  });
  return buildIndex(files);
}

const REPO_ROOT = path.resolve(fileURLToPath(new URL('..', import.meta.url)));

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  // Always the repository root, whatever the cwd: the hook and the gate call this from anywhere.
  const fresh = generateIndex(REPO_ROOT);
  const target = path.join(REPO_ROOT, INDEX_FILE);
  if (process.argv.includes('--check')) {
    const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (current === fresh) {
      process.stdout.write(`${INDEX_FILE} is fresh\n`);
    } else {
      process.stderr.write(
        `${INDEX_FILE} is STALE — run \`npm run code-index\` (the pre-commit hook does this automatically)\n`,
      );
      process.exitCode = 1;
    }
  } else {
    writeFileSync(target, fresh, 'utf8');
    process.stdout.write(`wrote ${INDEX_FILE}\n`);
  }
}
